### ISSUE TITLE
shortening standard assertion error message

### ISSUE THREAD

**Issue by ORESoftware** [shouldjs/should.js#108]
Right now I get this

```js
✘  => test fail   "tests 6"
	AssertionError: expected TestSuiteBase {
      after: Function { name: '' },
      afterEach: Function { name: '' },
      before: Function { name: '' },
      beforeEach: Function { name: '' },
      context: Function {
        ONLY: Function { name: '' },
        SKIP: Function { name: '' },
        only: Function { name: '' },
        skip: Function { name: '' },
        name: ''
      },
      desc: 'loop',
      describe: Function {
        ONLY: Function { name: '' },
        SKIP: Function { name: '' },
        only: Function { name: '' },
        skip: Function { name: '' },
        name: ''
      },
      it: Function {
        ONLY: Function { name: '' },
        SKIP: Function { name: '' },
        only: Function { name: '' },
        skip: Function { name: '' },
        name: ''
      },
      opts: Object {},
      parent: Object { desc: 'Suite7', parallel: false, testId: 0, title: 'Suite7' },
      skipped: false,
      title: 'loop'
    } to have property name
        at Assertion.fail (c:\Users\denman\WebstormProjects\suman-private\node_modules\should\lib\assertion.js:92:17)
        at Assertion.Object.defineProperty.value [as property] (c:\Users\denman\WebstormProjects\suman-private\node_modules\should\lib\assertion.js:164:19)
        at TestSuiteBase.<anonymous> (c:\Users\denman\WebstormProjects\suman-private\test\build-tests\tes-t7.jsx:39:34)
        at c:\Users\denman\WebstormProjects\suman-private\lib\test-suite-helpers\handle-test.js:158:56
        at doNTCallback0 (node.js:419:9)
        at Immediate._tickDomainCallback [as _onImmediate] (node.js:389:13)
        at processImmediate [as _immediateCallback] (timers.js:383:17)
```

I am wondering if there is some setting I can use with should such that the above might become

```js
 ✘  => test fail   "tests 6"
	AssertionError: expected TestSuiteBase {} to have property "name"
```

in other words I would like to eliminate the properties inside the object and possibly put quotes around the property name, so that it becomes property "name"

any ideas here? thanks

**Comment by btd** [comment]
Hi, sorry for very late response, i just forgot about this issue.
I do not think this issue easy fixable, because format messages are very subjective. I can only suggest to add custom formating to should-format.

**Comment by ORESoftware** [comment]
Ok, thanks for the tip, which try that out
