### ISSUE TITLE
Comparaison of arrays of resolved promises

### ISSUE THREAD

**Issue by fmichaud** [shouldjs/should.js#168]
Hello,

My function is returning an array of [Bluebird promises](http://bluebirdjs.com/). When they're resolved, I'm getting for each promise a boolean :

```javascript
  it('should be finally equal to {true}', () => {
    return (WaitForIt.factory().add('www.google.com:80').wait()).should.be.finally.equal([true]);
  });
```

Running unit tests using mocha occurs a curious error:

```
AssertionError: expected Array [ true ] to be Array [ true ]
    at Assertion.fail (node_modules/should/cjs/should.js:275:17)
    at Assertion.value (node_modules/should/cjs/should.js:356:19)
    at node_modules/should/cjs/should.js:387:24
    at <anonymous>
```

I'm using :
* should.js v13.2.1
* node v9.5.0
* bluebird v3.5.1.

Thanks for your help !

**Comment by btd** [comment]
👍
