### ISSUE TITLE
Can't parse headers when using `.options()`

### ISSUE THREAD

**Issue by diosney** [shouldjs/should.js#77]
The following is the test definition:

```js
api = supertest(url);

describe('when OPTIONS', function () {
    it('should return only method GET', function (done) {
      api
        .options('/')
        .expect('Allow', 'GET')
        .expect(200, done);
    });
  });
```

Its keeping triggering the following error:

```
Uncaught TypeError: Cannot read property 'header' of undefined
      at _stream_readable.js:944:16
```

When

```js
 api
        .options('/')
        .end(function(error,res){
          if (error) return done(error);
          done()
        });
```

It says:

```
SyntaxError: Unexpected token G
      at Object.parse (native)
      at _stream_readable.js:944:16
```

I already tried a lot of things without being able to make this work.
I 'm using supertest `^1.0.1` and it worked fine with version `~0.13.0`.

Thanks

**Comment by diosney** [comment]
Oops, sorry, wrong repo/issue :(
